CREATE TABLE "USERS" (
    "ID" INTEGER not null primary key,
	"NAME" VARCHAR(255) not null,
	"EMAIL" VARCHAR(255) not null,
	"PASSWORD" VARCHAR(255) not null,
	"PASSWORD_RESET_TOKEN" VARCHAR(255)
)

CREATE TABLE "ROLES" (
    "ID" INTEGER not null primary key,
	"NAME" VARCHAR(255) not null,
	"DESCRIPTION" VARCHAR(1024)
)

CREATE TABLE "PERMISSIONS" (
    "ID" INTEGER not null primary key,
	"NAME" VARCHAR(255) not null,
	"DESCRIPTION" VARCHAR(1024)
)

CREATE TABLE ROLE_PERMISSION (
    "ROLE_ID" INTEGER CONSTRAINT RP_ROLES_FK REFERENCES ROLES,
    "PERM_ID" INTEGER CONSTRAINT RP_PERMISSIONS_FK REFERENCES PERMISSIONS
)

CREATE TABLE USER_ROLE (
    "ROLE_ID" INTEGER CONSTRAINT UR_ROLES_FK REFERENCES ROLES,
    "USER_ID" INTEGER CONSTRAINT UR_USERS_FK REFERENCES USERS
)

CREATE TABLE "CATEGORIES" (
    "ID" INTEGER not null primary key,
	"NAME" VARCHAR(255) not null,
	"DISP_ORDER" INTEGER,
	"DESCRIPTION" VARCHAR(1024)
)

CREATE TABLE "CUSTOMERS" (
    "ID" INTEGER not null primary key,
	"FIRSTNAME" VARCHAR(255) not null,
	"LASTNAME" VARCHAR(255),
	"EMAIL" VARCHAR(255),
	"PHONE" VARCHAR(255),
	"PASSWORD" VARCHAR(255) not null
)

CREATE TABLE "PAYMENT" (
    "ID" INTEGER not null primary key,
	"CC_NUMBER" VARCHAR(255),
	"CVV" VARCHAR(255),
	"AMOUNT" DECIMAL(19,2)
)

CREATE TABLE "ADDRESSES" (
    "ID" INTEGER not null primary key,
	"ADDRESSLINE1" VARCHAR(255),
	"ADDRESSLINE2" VARCHAR(255),
	"CITY" VARCHAR(255),
	"STATE" VARCHAR(255),
	"ZIPCODE" VARCHAR(255),
	"COUNTRY" VARCHAR(255) 
)

CREATE TABLE "PRODUCTS" (
    "ID" INTEGER not null primary key,
	"NAME" VARCHAR(255) not null,
	"DESCRIPTION" VARCHAR(1024),
	"SKU" VARCHAR(255) not null,
	"PRICE" DECIMAL(19,2) not null,
	"IMAGEURL" VARCHAR(255),
	"CREATED_ON" TIMESTAMP,
    "CAT_ID" INTEGER CONSTRAINT PR_CAT_FK REFERENCES CATEGORIES
)

CREATE TABLE "ORDERS" (
    "ID" INTEGER not null primary key,
	"STATUS" VARCHAR(255),
	"CREATED_ON" TIMESTAMP,
    "CUST_ID" INTEGER CONSTRAINT OR_CUST_ID_FK REFERENCES CUSTOMERS,
    "DELIVERY_ADDR_ID" INTEGER CONSTRAINT OR_DELIVERY_ADDR_FK REFERENCES ADDRESSES,
    "PAYMENT_ID" INTEGER CONSTRAINT OR_PAYMENT_FK REFERENCES PAYMENT,
    "BILLING_ADDR_ID" INTEGER CONSTRAINT OR_BILLING_ADDR_FK REFERENCES ADDRESSES
)

CREATE TABLE "ORDER_ITEMS" (
    "ID" INTEGER not null primary key,
	"QUANTITY" INTEGER not null,
	"PRICE" DECIMAL(19,2),
    "ORDER_ID" INTEGER CONSTRAINT OI_ORDER_FK REFERENCES ORDERS,
    "PRODUCT_ID" INTEGER CONSTRAINT OI_PRODUCT_FK REFERENCES PRODUCTS
)
